const quotes = {
  "Abaddon": "Default hero best hero.",
  "Alchemist": "YOU get an aghs and YOU get an aghs and YOU get an aghs!",
  "Ancient Apparition": "Blessed ice!",
  "Anti Mage": "I have finished farming–the fun ends now.",
  "Arc Warden": "",
  "Axe": "",
  "Bane": "",
  "Batrider": "",
  "Beastmaster": "",
  "Bristleback": "",
  "Broodmother": "",
  "Centaur Warrunner": "",
  "Chaos Knight": "",
  "Chen": "",
  "Clinkz": "",
  "Clockwerk": "",
  "Crystal Maiden": "",
  "Dark Seer": "",
  "Dazzle": "",
  "Death Prophet": "Well done, my beauties!",
  "Disruptor": "",
  "Doom": "",
  "Dragon Knight": "",
  "Drow Ranger": "",
  "Earth Spirit": "",
  "Earthshaker": "SLAMMIN'",
  "Elder Titan": "",
  "Ember Spirit": "",
  "Enchantress": "",
  "Enigma": "",
  "Faceless Void": "",
  "Gyrocopter": "",
  "Huskar": "",
  "Invoker": "",
  "Io": "Beep boop? (Arcana was rigged #neverforget)",
  "Jakiro": "",
  "Juggernaut": "",
  "Keeper Of The Light": "",
  "Kunkka": "",
  "Legion Commander": "#1 jungler.",
  "Leshrac": "Disco Pony",
  "Lich": "",
  "Lifestealer": "",
  "Lina": "",
  "Lion": "",
  "Lone Druid": "",
  "Luna": "",
  "Lycan": "",
  "Magnus": "",
  "Medusa": "",
  "Meepo": "",
  "Mirana": "Shadows, take us!",
  "Monkey King": "",
  "Morphling": "",
  "Naga Siren": "",
  "Nature's Prophet": "FURION TP NOW",
  "Necrophos": "",
  "Night Stalker": "",
  "Nyx Asassin": "Nyx nyx nyx nyx nyx",
  "Ogre Magi": "",
  "Omniknight": "",
  "Oracle": "",
  "Outworld Devourer": "",
  "Phantom Assassin": "",
  "Phantom Lancer": "",
  "Phoenix": "Bawk bawk",
  "Puck": "Your million dollar Dream Coil awaits.",
  "Pudge": "",
  "Pugna": "",
  "Queen Of Pain": "",
  "Razor": "",
  "Riki": "",
  "Rubick": "",
  "Sand King": "",
  "Shadow Demon": "",
  "Shadow Fiend": "",
  "Shadow Shaman": "",
  "Silencer": "",
  "Skywrath Mage": "",
  "Slardar": "",
  "Slark": "",
  "Sniper": "Ho ho, ha ha!",
  "Spectre": "",
  "Spirit Breaker": "Bash Lord incoming.",
  "Storm Spirit": "",
  "Sven": "",
  "Techies": "Wrecking pubs since 2014.",
  "Templar Assassin": "",
  "Terrorblade": "",
  "Tidehunter": "",
  "Timbersaw": "",
  "Tinker": "",
  "Tiny": "",
  "Treant Protector": "",
  "Troll Warlord": "Please do feed the trolls.",
  "Tusk": "",
  "Underlord": "",
  "Undying": "",
  "Ursa": "",
  "Vengeful Spirit": "",
  "Venomancer": "",
  "Viper": "",
  "Visage": "",
  "Warlock": "",
  "Weaver": "Skitter back!",
  "Windranger": "",
  "Winter Wyvern": "",
  "Witch Doctor": "",
  "Wraith King": "Skeleton King forever.",
  "Zeus": "> Zeus ult now!"
}

module.exports = quotes;
